version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing frontend dependencies...
      - cd photo-album && npm install
  build:
    commands:
      - echo Building Vite application...
      - cd photo-album && npm run build

artifacts:
  base-directory: photo-album/dist
  files:
    - '**/*'
