version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing frontend dependencies...
      - npm install
    working-directory: photo-album
  build:
    commands:
      - echo Building Vite application...
      - npm run build
    working-directory: photo-album

artifacts:
  base-directory: photo-album/dist
  files:
    - '**/*'
