AWSTemplateFormatVersion: '2010-09-09'
Description: AI Photo Search Application Infrastructure

Parameters:
  OpenSearchUser:
    Type: String
    Default: dr3432
  OpenSearchPass:
    Type: String
    NoEcho: true
    Default: "#Tipo123"
  ExistingOpenSearchEndpoint:
    Type: String
    Default: "https://search-photos-azg567v37deut3tsvvucmickne.aos.us-east-1.on.aws"
  LexBotId:
    Type: String
  LexBotAliasId:
    Type: String
  OpenSearchDomainName:
    Type: String
    Default: photos
  FrontendBucketName:
    Type: String
    Default: photo-search-v1-frontend-bucket
  PhotosBucketName:
    Type: String
    Default: photo-storage-bucket-b2-v1 

Resources:
  # S3 Buckets
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FrontendBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  PhotosBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    DependsOn: LF1S3Permission
    Properties:
      BucketName: !Ref PhotosBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LF1IndexPhotos.Arn

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${FrontendBucket}/*"

  # IAM Roles
  LF1ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LF1Permissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:HeadObject
                Resource: !Sub "arn:aws:s3:::${PhotosBucketName}/*"
              - Effect: Allow
                Action: rekognition:DetectLabels
                Resource: '*'

  LF2ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LF2Permissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lex:RecognizeText
                Resource: '*'
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub "arn:aws:s3:::${PhotosBucketName}/*"

  ApiGatewayS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ApiS3Permissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub "arn:aws:s3:::${PhotosBucketName}/*"

  # Lambda Functions
  LF1IndexPhotos:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index-photos.lambda_handler
      Role: !GetAtt LF1ExecutionRole.Arn
      Code: ./backend/lf1
      Runtime: python3.9
      Environment:
        Variables:
          OPENSEARCH_ENDPOINT: !Ref ExistingOpenSearchEndpoint
          OS_USER: !Ref OpenSearchUser
          OS_PASS: !Ref OpenSearchPass

  LF2SearchPhotos:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: search-photos-v1
      Handler: search-photos.lambda_handler
      Role: !GetAtt LF2ExecutionRole.Arn
      Code: ./backend/lf2
      Runtime: python3.9
      Timeout: 20
      Environment:
        Variables:
          OPENSEARCH_ENDPOINT: !Ref ExistingOpenSearchEndpoint
          LEX_BOT_ID: !Ref LexBotId
          LEX_BOT_ALIAS_ID: !Ref LexBotAliasId
          OS_USER: !Ref OpenSearchUser
          OS_PASS: !Ref OpenSearchPass
          S3_BUCKET: !Ref PhotosBucketName


  # S3 Permission for Lambda Trigger
  LF1S3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LF1IndexPhotos.Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:aws:s3:::${PhotosBucketName}"

  LF2ApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LF2SearchPhotos.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PhotoApi}/*"

  # API Gateway
  PhotoApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: PhotoAlbumAPI
      BinaryMediaTypes:
        - 'image/png'
        - 'image/jpg'
        - 'image/jpeg'
        - 'image/bmp'
        - 'image/webp'
        - 'image/tiff'
        - 'image/*'
        - 'application/octet-stream'
        - '*/*'
      Body:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./swagger.yaml

  # API Deployment & Stage
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: PhotoApi
    Properties:
      RestApiId: !Ref PhotoApi

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref PhotoApi
      DeploymentId: !Ref ApiDeployment
      StageName: v1

Outputs:
  FrontendBucketName:
    Value: !Ref FrontendBucket
    Export:
      Name: photo-search-stack-FrontendBucketName
  WebsiteURL:
    Value: !GetAtt FrontendBucket.WebsiteURL
  ApiURL:
    Value: !Sub "https://${PhotoApi}.execute-api.${AWS::Region}.amazonaws.com/v1"
  RestApiId:
    Value: !Ref PhotoApi

